/*
 * resnet_infer.h
 *
 * Shared interface header for ARM <-> DSP communication via FastRPC.
 *
 * In a full Hexagon SDK build this header is auto-generated by qaic from
 * resnet_infer.idl.  The version here is a manual equivalent so the project
 * compiles without running the IDL compiler first.
 */

#ifndef RESNET_INFER_H
#define RESNET_INFER_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ------------------------------------------------------------------ */
/*  Return codes                                                       */
/* ------------------------------------------------------------------ */
#ifndef AEE_SUCCESS
#define AEE_SUCCESS            0
#endif
#ifndef AEE_EFAILED
#define AEE_EFAILED            1
#endif
#ifndef AEE_ENOMEMORY
#define AEE_ENOMEMORY          2
#endif
#ifndef AEE_EBADPARM
#define AEE_EBADPARM           5
#endif
#ifndef AEE_ENOTINITIALIZED
#define AEE_ENOTINITIALIZED    6
#endif

typedef int AEEResult;

/* ------------------------------------------------------------------ */
/*  Parameter IDs for get_param / set_param                            */
/* ------------------------------------------------------------------ */
#define RESNET_PARAM_INPUT_WIDTH      0
#define RESNET_PARAM_INPUT_HEIGHT     1
#define RESNET_PARAM_INPUT_CHANNELS   2
#define RESNET_PARAM_NUM_CLASSES      3
#define RESNET_PARAM_CONFIDENCE_THR   4   /* fixed-point: value / 1000 */

/* ------------------------------------------------------------------ */
/*  Model constants                                                    */
/* ------------------------------------------------------------------ */
#define RESNET_INPUT_H         224
#define RESNET_INPUT_W         224
#define RESNET_INPUT_C         3
#define RESNET_NUM_CLASSES     10

/* Sizes in bytes */
#define RESNET_INPUT_SIZE      (RESNET_INPUT_C * RESNET_INPUT_H * RESNET_INPUT_W * (int)sizeof(float))
#define RESNET_OUTPUT_SIZE     (RESNET_NUM_CLASSES * (int)sizeof(float))

/* ------------------------------------------------------------------ */
/*  FastRPC interface functions                                        */
/*                                                                     */
/*  These map 1-to-1 to the IDL methods.  On the ARM side the stub    */
/*  implementation marshals arguments across FastRPC.  On the DSP side */
/*  resnet_infer_imp.cpp provides the real implementation.             */
/* ------------------------------------------------------------------ */

/*
 * Load the model and allocate DSP resources.
 *   model_path     – null-terminated path to the QNN model library / context
 *                    binary on the device filesystem.
 *   model_path_len – length of the string including the null terminator.
 */
AEEResult resnet_infer_init(const char *model_path,
                            int         model_path_len);

/*
 * Release all DSP resources.  Safe to call even when not initialised.
 */
AEEResult resnet_infer_deinit(void);

/*
 * Set a runtime parameter before or between process() calls.
 */
AEEResult resnet_infer_set_param(int param_id,
                                 int value);

/*
 * Query a runtime / model parameter.
 */
AEEResult resnet_infer_get_param(int  param_id,
                                 int *value);

/*
 * Run inference on one preprocessed frame.
 *
 *   input_data        – CHW float32 tensor as raw bytes
 *                       (expected size: RESNET_INPUT_SIZE)
 *   input_data_len    – byte length of input_data
 *   output_data       – caller-allocated buffer that receives the 10-class
 *                       logits as float32 (size >= RESNET_OUTPUT_SIZE)
 *   output_data_len   – capacity of output_data in bytes
 *   output_data_lenout – actual bytes written to output_data
 */
AEEResult resnet_infer_process(const uint8_t *input_data,
                               int            input_data_len,
                               uint8_t       *output_data,
                               int            output_data_len,
                               int           *output_data_lenout);

#ifdef __cplusplus
}
#endif

#endif /* RESNET_INFER_H */
